$(function(){
  //OPENボタンをクリックでイベント発生
  $(".modal_open_button").on("click",function(){
    //グレーの背景をフェードインで表示
    $(".modal_win").fadeIn();
  });
  //クローズボタンをクリックするとイベント発生
  $(".modal_close_button").on("click",function(){
    //モーダルのウィンドウをフェードアウトにする処理
    $(".modal_win").fadeOut();
  });
});